import 'pokemon_model.dart';

List<Pokemon> allPokemon = [
  Pokemon(
    name: "Bulbasaur",
    type: "Grass / Poison",
    hp: "45", atk: "49", def: "49", spAtk: "65", spDef: "65", speed: "45",
    ability: "Overgrow",
    weakness: "Fire, Ice, Flying, Psychic",
    description: "Bulbasaur adalah Pokémon yang mengandalkan keseimbangan antara offense dan defense. Tanaman di punggungnya menyimpan energi matahari untuk memperkuat serangan.",
    role: "Support / Tank awal game (Sustain: Leech Seed + Sleep Powder)",
    imagePath: "assets/bulbasaur.png",
  ),
  Pokemon(
    name: "Charizard",
    type: "Fire / Flying",
    hp: "78", atk: "84", def: "78", spAtk: "109", spDef: "85", speed: "100",
    ability: "Blaze",
    weakness: "Rock (x4), Water, Electric",
    description: "Charizard adalah attacker cepat dengan damage tinggi, terutama di Special Attack. Sangat berbahaya tapi punya kelemahan besar terhadap Rock-type.",
    role: "Special Attacker / Sweeper (Burst damage)",
    imagePath: "assets/charizard.png",
  ),
  Pokemon(
    name: "Blastoise",
    type: "Water",
    hp: "79", atk: "83", def: "100", spAtk: "85", spDef: "105", speed: "78",
    ability: "Torrent",
    weakness: "Electric, Grass",
    description: "Blastoise adalah tank kuat dengan defense tinggi. Cocok untuk bertahan lama dan memberikan tekanan stabil.",
    role: "Tank / Defensive Support (Wall in team)",
    imagePath: "assets/blastoise.png",
  ),
  Pokemon(
    name: "Pikachu",
    type: "Electric",
    hp: "35", atk: "55", def: "40", spAtk: "50", spDef: "50", speed: "90",
    ability: "Static",
    weakness: "Ground",
    description: "Pikachu adalah Pokémon cepat dengan serangan listrik yang efektif melawan Water dan Flying. Tapi cukup rapuh.",
    role: "Fast Attacker / Utility (Status Paralyze)",
    imagePath: "assets/pikachu.png",
  ),
  Pokemon(
    name: "Gengar",
    type: "Ghost / Poison",
    hp: "60", atk: "65", def: "60", spAtk: "130", spDef: "75", speed: "110",
    ability: "Cursed Body",
    weakness: "Ghost, Dark, Psychic",
    description: "Gengar adalah glass cannon dengan Special Attack tinggi dan kecepatan luar biasa. Cocok untuk menghabisi lawan dengan cepat.",
    role: "Special Sweeper (Hit & run playstyle)",
    imagePath: "assets/gengar.png",
  ),
  Pokemon(
    name: "Dragonite",
    type: "Dragon / Flying",
    hp: "91", atk: "134", def: "95", spAtk: "100", spDef: "100", speed: "80",
    ability: "Inner Focus",
    weakness: "Ice (x4), Rock, Dragon, Fairy",
    description: "Dragonite adalah pseudo-legendary dengan stat tinggi di hampir semua aspek. Walau terlihat ramah, dia sangat kuat di battle.",
    role: "Physical Sweeper / All-rounder",
    imagePath: "assets/dragonite.png",
  ),
  Pokemon(
    name: "Snorlax",
    type: "Normal",
    hp: "160", atk: "110", def: "65", spAtk: "0", spDef: "110", speed: "30",
    ability: "Thick Fat",
    weakness: "Fighting",
    description: "Snorlax adalah tank dengan HP besar. Sulit dikalahkan dan bisa jadi tembok tim.",
    role: "Tank / Wall",
    imagePath: "assets/snorlax.png",
  ),
  Pokemon(
    name: "Eevee",
    type: "Normal",
    hp: "55", atk: "55", def: "50", spAtk: "45", spDef: "65", speed: "55",
    ability: "Adaptability",
    weakness: "Fighting",
    description: "Eevee unik karena punya banyak evolusi (Eeveelutions). Fleksibel sesuai kebutuhan tim.",
    role: "Flexible / Support",
    imagePath: "assets/eevee.png",
  ),
  Pokemon(
    name: "Vaporeon",
    type: "Water",
    hp: "130", atk: "65", def: "60", spAtk: "110", spDef: "95", speed: "65",
    ability: "Water Absorb",
    weakness: "Electric, Grass",
    description: "Tank spesial dengan HP besar dan sustain tinggi.",
    role: "Special Tank / Support",
    imagePath: "assets/vaporeon.png",
  ),
  Pokemon(
    name: "Jolteon",
    type: "Electric",
    hp: "65", atk: "65", def: "60", spAtk: "110", spDef: "95", speed: "130",
    ability: "Volt Absorb",
    weakness: "Ground",
    description: "Salah satu Pokémon tercepat. Cocok untuk strike cepat.",
    role: "Fast Special Sweeper",
    imagePath: "assets/jolteon.png",
  ),
  Pokemon(
    name: "Flareon",
    type: "Fire",
    hp: "65", atk: "130", def: "60", spAtk: "95", spDef: "110", speed: "65",
    ability: "Flash Fire",
    weakness: "Water, Ground, Rock",
    description: "Damage fisik tinggi tapi agak lambat.",
    role: "Physical Attacker",
    imagePath: "assets/flareon.png",
  ),
  Pokemon(
    name: "Lucario",
    type: "Fighting / Steel",
    hp: "70", atk: "110", def: "70", spAtk: "115", spDef: "70", speed: "90",
    ability: "Steadfast / Inner Focus",
    weakness: "Fire, Fighting, Ground",
    description: "Fighter dengan aura power, bisa mixed attacker.",
    role: "Mixed Sweeper",
    imagePath: "assets/lucario.png",
  ),
  Pokemon(
    name: "Greninja",
    type: "Water / Dark",
    hp: "72", atk: "95", def: "67", spAtk: "103", spDef: "71", speed: "122",
    ability: "Protean",
    weakness: "Grass, Electric, Fighting, Bug, Fairy",
    description: "Ninja Pokémon super cepat dengan ability unik (Protean).",
    role: "Speed Sweeper",
    imagePath: "assets/greninja.png",
  ),
  Pokemon(
    name: "Machamp",
    type: "Fighting",
    hp: "90", atk: "130", def: "80", spAtk: "65", spDef: "85", speed: "55",
    ability: "No Guard / Guts",
    weakness: "Flying, Psychic, Fairy",
    description: "Petarung kuat dengan 4 tangan.",
    role: "Physical Attacker",
    imagePath: "assets/machamp.png",
  ),
  Pokemon(
    name: "Alakazam",
    type: "Psychic",
    hp: "55", atk: "50", def: "45", spAtk: "135", spDef: "95", speed: "120",
    ability: "Synchronize / Inner Focus",
    weakness: "Bug, Ghost, Dark",
    description: "Glass cannon dengan kecerdasan tinggi.",
    role: "Special Sweeper",
    imagePath: "assets/alakazam.png",
  ),
  Pokemon(
    name: "Gyarados",
    type: "Water / Flying",
    hp: "95", atk: "125", def: "79", spAtk: "60", spDef: "100", speed: "81",
    ability: "Intimidate",
    weakness: "Electric (x4), Rock",
    description: "Agresif dan kuat secara fisik.",
    role: "Physical Sweeper",
    imagePath: "assets/gyarados.png",
  ),
  Pokemon(
    name: "Tyranitar",
    type: "Rock / Dark",
    hp: "100", atk: "134", def: "110", spAtk: "95", spDef: "100", speed: "61",
    ability: "Sand Stream",
    weakness: "Fighting (x4), Grass, Water, Steel, Ground, Bug, Fairy",
    description: "Tank + attacker kuat, summon sandstorm.",
    role: "Tank / Sweeper",
    imagePath: "assets/tyranitar.png",
  ),
];